sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: l3wktL+6Tbj6ubWrY6Lsg60Qt/GqOxP66Z02sHzrj1z6o5rW3jJwkks3lVqE03Ejk+Ho9xMk2GY4zYiWgMpKAhjv63aNMGCqhUQYnGoZ1STV/QA37sWXTn8VHews7KbxciFU4o41TmPdCt+1cBe6Mhrx67fF1gdRPgwZ+6irzdXeq+4c5lxwvOU3Rp+Vrxd/+RTKf/7JYxWexF9BvAzQF0Hxtua4Qrm2epuluNNN54AO/kv0TxkCF5Td/wkc6Tn0WPzp5I0Ge6rckq3HYsQR+j1PMP4kKGzmJuk4lt3k5m9KUtP06smqLEuxDgmUxxjQVY8os4EOHLZUoNnJjzOH1kQG23BZEMjzjLexi0xPy8iv8ONkNuTrYcyL4z8r/24VxQ8zcxogJsltQWo2RLo4gN+4WCoog3p5c62YV+ZvSoxmI7HCHpualTDkj2x+AaEAw0se01Zr9OumGd3fUYmXxOp2OviRBYAN2K1pat+6S3KwbhF/SRJ1AK4L/mRhHYEinm6c5wFrbZC1Yk0GYhEkFedLzvbR4X08vSk9rVP6A7W8tqt4O0Z+D7EEp93ONoIyqqE5VAQ8yMs7FuxGNu3m+OUYIQpkmGmuMNiDfkek/j1nSSv5FGSsO4dyjRdu8tSbjK9F2Eaz8HIRoX7LYz4xaiFawJtD8KDz2BCzinVj7hU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Elissa--Or-The-Doom-of-Zimbabwe_2855
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy